### ISSUE TITLE
Rtl9210 sata support

### ISSUE THREAD

**Issue by yasinvs** [bensuperpc/rtl9210#4]
Good day, I have an orico box, it supports NVME, but how can I add ngff sata support? I know that normally there is rtl9210b on the device, so I set the firmware to 1.33.44.

**Comment by yasinvs** [comment]
Model M2PV-C3-BK-EP

**Comment by yasinvs** [comment]
**************************************************************
Device : [Port4] : Realtek RTL9210B-CG #0
**************************************************************
U2PHY : n/a
U3PHY : n/a
VID : 0x0bda
PID : 0x9210
MANUFACTURE : "Realtek"
PRODUCT : "Realtek"
SERIAL : "012345678909"
SCSI_PRODUCT : "RTL9210B-CG     "
SCSI_VENDOR : "Realtek "
USB_SELF_PWR : n/a
DISK_HOTPLUG : 0x00
LED : n/a
PINMUX1 : 0x00000000
PINMUX2 : 0x00000000
U2_MAXPWR : 0xfa
U3_MAXPWR : 0x70
ASPMDIS : 0x00
PCIE_REFCLK : n/a
DISK_IPS_THRES : 0x00
SWR_1_2V : n/a
EN_UPS : n/a
PD : n/a
CUSTOMIZED_LED : 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 
SUSPEND_LED_OFF : 0x01
FORCE_USB_SPEED : n/a
FORCE_PCIE_SPEED : n/a
EN_U1U2 : n/a
FORCE_USB_QUIRK : n/a
FORCE_PCIE_QUIRK : n/a
FAN : 0x00000000
DIS_SHOW_EMPTY_DISK : n/a
FORCE_SATA_NORMAL_DMA : n/a
UART_DBG_PIN : 0x05
FINGER_PRINT_EN : n/a
RM_INTERNAL_RD : n/a
HS_AUTO_SWITCH : 0x05
UART_BAUD_RATE : n/a
CUSTOMIZED_DISK_IDENTIFY : n/a
HW_LED_CFG : n/a
CDROM_CFG : n/a
SUPPORT_HID : n/a
LATE_INIT_DISK : n/a
SCSI_WP_PIN : n/a
SD_MMC_TYPE : n/a
FORCE_PORT_TYPE : n/a
BCDDEVICE : n/a
SUSPEND_DISK_OFF : 0x01
SCSI_WB_PIN : n/a
CUSTOMIZED_FEATURE : n/a
PERIPH_API : n/a
RAID_CFG : n/a

Boot Mode : Flash
FW Ver : 1.33.44
FW Build Date : 2024.01.18
IC Pkg Type : PCIE
UUID : n/a

Disconn_ForceUSB2 : false

**Comment by bensuperpc** [comment]
Thank you for your contribution, it is added: 01960b4397021b18b5d421b655488a2d6410203a

By default, M.2 SATA support is enabled on RTL9210B devices

**Comment by yasinvs** [comment]
> Katkınız için teşekkür ederiz, eklendi: [01960b4](https://github.com/bensuperpc/rtl9210/commit/01960b4397021b18b5d421b655488a2d6410203a)
> 
> Varsayılan olarak, M.2 SATA desteği RTL9210B cihazlarda etkindir

You're Welcome :)

**Comment by yasinvs** [comment]
You're Welcome :)
